[package]
name = "demo-redv-rust"
edition = "2021"
version = "0.1.0"

[lib]
path = "src/lib.rs"
name = "demo_redv_rust"
edition = "2021"
crate-type = ["staticlib"]
required-features = []

[dependencies]
e310x-hal = "0.9.3"
